services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongo-data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    env_file:
      - .env
volumes:
  mongo-data:
